# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBFftGWCm-2CT1sJHAs5l8JCJtUjV454
"""

! pip install transformers torch pandas

from transformers import pipeline
import pandas as pd
#load sentiment analysis model
sentiment=pipeline("sentiment-analysis")
#sample product review
review="""The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for working videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Overall. it is a good laptop for student but not for giving.
"""
#split review into sentences
sentences=review.split(".")
pros=[]
cons=[]
for s in sentences:
  s=s.strip();
  if s=="":
    continue
    result=sentiment(s)[0]
    if result["label"]=="POSITIVE":
      pros.append(s)
    elif result["label"]=="NEGATIVE":
      cons.append
#take only 2 pros and cons
pros=pros[:2]
cons=cons[:2]
#create table
df=pd.DataFrame({
    "Pros":pros,
    "Cons":cons
})
df