# -*- coding: utf-8 -*-
"""similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmV7a-LGUkax0ZvaGtaKfniwzDx7m76S
"""

!pip install sentence_transformers

from sentence_transformers import SentenceTransformer,util
#load the model
model=SentenceTransformer ('all-MiniLM-L6-V2')
#Take input from user
text1=input("enter text1: ")
text2=input("enter text2: ")
#covert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\n similarity score:",round(float(similarity),2))
if similarity>0.75:
  print("similarity level:high")
elif similarity>0.4:
  print("similarity level:medium")
else :
  print("similarity level:low")