# -*- coding: utf-8 -*-
"""text code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUhA3XvE2vc7lAWxXKcsFc5Cdm5apRQZ
"""

! pip install transformers torch

from transformers import pipeline
# load text generation model (GENAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
# Input prompt
prompt="Artifical Intelligence in finance will"
# Generate text
result = generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])